name = "Nonconvex"
uuid = "01bcebdf-4d21-426d-b5c4-6132c1619978"
authors = ["Mohamed Tarek <mohamed82008@gmail.com> and contributors"]
version = "1.0.1"

[deps]
NonconvexCore = "035190e5-69f1-488f-aaab-becca2889735"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
NonconvexCore = "0.1"
Reexport = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
