name = "Nonconvex"
uuid = "01bcebdf-4d21-426d-b5c4-6132c1619978"
authors = ["Mohamed Tarek <mohamed82008@gmail.com> and contributors"]
version = "0.7.3"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
